#!/bin/bash
echo "=== .env.local 설정 ==="
echo "Vercel Dashboard → Settings → Environment Variables에서"
echo "각 값을 복사해서 아래에 붙여넣으세요."
echo ""

read -p "NOTION_TOKEN: " NOTION_TOKEN
read -p "NOTION_DB_RAW_ID: " NOTION_DB_RAW_ID
read -p "NOTION_DB_USERS_ID: " NOTION_DB_USERS_ID
read -p "NOTION_DB_WEEKLY_ID: " NOTION_DB_WEEKLY_ID
read -p "NOTION_DB_COMMENTS_ID: " NOTION_DB_COMMENTS_ID
read -p "CLOUDINARY_CLOUD_NAME: " CLOUDINARY_CLOUD_NAME
read -p "CLOUDINARY_API_KEY: " CLOUDINARY_API_KEY
read -p "CLOUDINARY_API_SECRET: " CLOUDINARY_API_SECRET

cat > .env.local << EOF
NOTION_TOKEN=${NOTION_TOKEN}
NOTION_DB_RAW_ID=${NOTION_DB_RAW_ID}
NOTION_DB_USERS_ID=${NOTION_DB_USERS_ID}
NOTION_DB_WEEKLY_ID=${NOTION_DB_WEEKLY_ID}
NOTION_DB_COMMENTS_ID=${NOTION_DB_COMMENTS_ID}
CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
CLOUDINARY_FOLDER=wonwoo-album
EOF

echo ""
echo "✅ .env.local 생성 완료!"
echo "이제 npm run build:pdf -- --month=2026-04 실행하세요."
